### ISSUE TITLE
Target of URI doesn't exist: 'package:cachedrun/cloudinary.dart'.  and The method 'uploadFile' isn't defined for the type '_UploadPageState'

### ISSUE THREAD

**Issue by Gursewak-Uppal** [Ansh-Rathod/Flutter-Tiktok-Videos#2]
<img width="880" alt="image" src="https://user-images.githubusercontent.com/28809960/220821753-ca5c1522-7fd9-4981-9332-5f3514a5ea19.png">

**Comment by SANKARAMDAS** [comment]
Same here, 
@Gursewak-Uppal did you find anything/any other way?

**Comment by Ansh-Rathod** [comment]
Hiii, sorry for holding up the issue.

the file is removed purposefully.

the file only contains the upload file function you can create another function

```
 Future<String> _uploadFile(String filePath, String folderName) async {
    var file = File(filePath);
    var basename = p.basename(filePath);

    final downloadUrl = await FirebaseStorage.instance
        .ref()
        .child(folderName)
        .child(basename)
        .putFile(file)
        .then((taskSnapshot) => taskSnapshot.ref.getDownloadURL());

    return downloadUrl;
  }
```

**Comment by wann2** [comment]
Could you please update the source codes about the above issue?

**Comment by Gursewak-Uppal** [comment]
> Hiii, sorry for holding up the issue.
> 
> the file is removed purposefully.
> 
> the file only contains the upload file function you can create another function
> 
> ```
>  Future<String> _uploadFile(String filePath, String folderName) async {
>     var file = File(filePath);
>     var basename = p.basename(filePath);
> 
>     final downloadUrl = await FirebaseStorage.instance
>         .ref()
>         .child(folderName)
>         .child(basename)
>         .putFile(file)
>         .then((taskSnapshot) => taskSnapshot.ref.getDownloadURL());
> 
>     return downloadUrl;
>   }
> ```

Works for me, Thanks @Ansh-Rathod
